### ISSUE TITLE
tests now broken

### ISSUE THREAD

**Issue by daogangtang** [paritytech/substrate-subxt#14]
Just pull the latest code, and open tests, run it, display below:

```
mike@DESKTOP-DC63SDI:~/works/substrate_works/substrate-subxt$ cargo test --release
   Compiling node-runtime v2.0.0 (https://github.com/paritytech/substrate/#337a0b22)
   Compiling substrate-subxt v0.1.0 (/home/mike/works/substrate_works/substrate-subxt)
    Finished release [optimized] target(s) in 1m 12s
     Running ../substrate/target/release/deps/substrate_subxt-ec0abb6820fe6c2b

running 6 tests
test tests::test_tx_contract_put_code ... FAILED
test tests::test_chain_read_metadata ... FAILED
test tests::test_tx_transfer_balance ... FAILED
test tests::test_chain_subscribe_blocks ... FAILED
test tests::test_chain_subscribe_finalized_blocks ... FAILED
test tests::test_state_read_free_balance ... FAILED

failures:

---- tests::test_tx_contract_put_code stdout ----
thread 'tests::test_tx_contract_put_code' panicked at 'called `Result::unwrap()` on an `Err` value: Rpc(ParseError("RuntimeVersion", Error("invalid type: string \"0xdf6acb689907609b\", expected an array of length 8", line: 0, column: 0)))', src/libcore/result.rs:999:5

---- tests::test_chain_read_metadata stdout ----
thread 'tests::test_chain_read_metadata' panicked at 'called `Result::unwrap()` on an `Err` value: Rpc(ParseError("RuntimeVersion", Error("invalid type: string \"0xdf6acb689907609b\", expected an array of length 8", line: 0, column: 0)))', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- tests::test_tx_transfer_balance stdout ----
thread 'tests::test_tx_transfer_balance' panicked at 'called `Result::unwrap()` on an `Err` value: Rpc(ParseError("RuntimeVersion", Error("invalid type: string \"0xdf6acb689907609b\", expected an array of length 8", line: 0, column: 0)))', src/libcore/result.rs:999:5

---- tests::test_chain_subscribe_blocks stdout ----
thread 'tests::test_chain_subscribe_blocks' panicked at 'called `Result::unwrap()` on an `Err` value: Rpc(ParseError("RuntimeVersion", Error("invalid type: string \"0xdf6acb689907609b\", expected an array of length 8", line: 0, column: 0)))', src/libcore/result.rs:999:5

---- tests::test_chain_subscribe_finalized_blocks stdout ----
thread 'tests::test_chain_subscribe_finalized_blocks' panicked at 'called `Result::unwrap()` on an `Err` value: Rpc(ParseError("RuntimeVersion", Error("invalid type: string \"0xdf6acb689907609b\", expected an array of length 8", line: 0, column: 0)))', src/libcore/result.rs:999:5

---- tests::test_state_read_free_balance stdout ----
thread 'tests::test_state_read_free_balance' panicked at 'called `Result::unwrap()` on an `Err` value: Rpc(ParseError("RuntimeVersion", Error("invalid type: string \"0xdf6acb689907609b\", expected an array of length 8", line: 0, column: 0)))', src/libcore/result.rs:999:5


failures:
    tests::test_chain_read_metadata
    tests::test_chain_subscribe_blocks
    tests::test_chain_subscribe_finalized_blocks
    tests::test_state_read_free_balance
    tests::test_tx_contract_put_code
    tests::test_tx_transfer_balance

test result: FAILED. 0 passed; 6 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
```

**Comment by daogangtang** [comment]
Solved in https://github.com/paritytech/substrate/issues/3482
